volumes:
        prometheus_data: {}
        grafana_data: {}
        postgres_data: {}
        mongo_data: {}
        redis_data: {}

services:
        backend:
                build: backend/
                ports:
                        - "8000:8000"
                depends_on:
                        - auth

        frontend:
                build: frontend/
                ports:
                        - "1080:3000"
                depends_on:
                        - backend

        prometheus:
                image: prom/prometheus
                ports:
                        - "8080:9090"
                volumes:
                        - ./prometheus/:/etc/prometheus/
                        - prometheus_data:/prometheus
                depends_on:
                        - backend

        grafana:
                image: grafana/grafana-oss
                ports:
                        - "3000:3000"
                volumes:
                        - grafana_data:/var/lib/grafana
                depends_on:
                        - prometheus

        postgres:
                image: postgres:15
                ports:
                        - "5432:5432"
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: peci

        auth:
                build: auth_server/
                ports:
                        - "9420:8000"
                depends_on:
                        - postgres

        mocknetworkcontroller:
                build: MockNetworkController/
                ports:
                        - "5000:5000"

        nginx:
                image: nginx
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                ports: 
                        - 80:80

        redis:
                image: redis:alpine
                command: redis-server
                ports:
                        - "6379:6379"
                volumes:
                        - redis_data:/data

        mongo:
                image: mongo:latest
                ports:
                        - "5511:27017"
                volumes:
                        - mongo_data:/data/db

        alertworkers:
                build:
                        context: ./AlertSystem/
                        dockerfile: WorkerRunner/Dockerfile
                depends_on:
                        - redis
                        - postgres

        alertserver:
                build: 
                        context: ./AlertSystem/
                        dockerfile: AlarmConfigurationApi/Dockerfile
                ports:
                        - "443:443"
                depends_on:
                        - redis
                        - postgres
