Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64"

    config.vm.disk :disk, size: "10GB"

    config.vm.provision :shell, path: "bootstrap.sh"                # Static. Will run the initial setup when the VM is deployed
end