version: "3.9"
services:
  flask:
    build: .
    container_name: flask
    restart: always
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./src/static/:/app/src/static/