name: Build Vue Page
on:
    push:
      branches:
        - website
    workflow_dispatch:
        
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: $commiter
        reponame: 'PECI-05-2022-23'
        token: ${{ secrets.GITHUB_TOKEN }}
    env:
       commiter: $GITHUB_ACTOR