name: Build Vue

on:
  push:
    branches: ["website"]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - run: | 
        cd peci-g5-2022-23
        npm install
        npm run build